# konan.properties
linuxArm64.clang=/Applications/DevEco-Studio.app/Contents/sdk/default/openharmony/native/llvm/bin/aarch64-linux-ohos-clang
linuxArm64.clangxx=/Applications/DevEco-Studio.app/Contents/sdk/default/openharmony/native/llvm/bin/aarch64-linux-ohos-clang++
linuxArm64.sysroot=/Applications/DevEco-Studio.app/Contents/sdk/default/openharmony/native/sysroot
linuxArm64.target=aarch64-linux-ohos